kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: qinchy-scheduler-clusterrolebinding
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: qinchy-scheduler-clusterrole
subjects:
  - kind: ServiceAccount
    name: qinchy-scheduler-serviceaccount
    namespace: kube-system